export const mockSubmissionRows = [
  {
    submissionId: "mock-1",
    date: "01/02/2026",
    essayType: "Practice",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: 7.5,
  },
  {
    submissionId: "mock-2",
    date: "03/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "General",
    taskType: "Task 1",
    score: 6.0,
  },
  {
    submissionId: "mock-3",
    date: "05/02/2026",
    essayType: "Practice",
    ieltsType: "Academic",
    taskType: "Task 1",
    score: 6.5,
  },
  {
    submissionId: "mock-4",
    date: "08/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: 7.0,
  },
  {
    submissionId: "mock-5",
    date: "11/02/2026",
    essayType: "Practice",
    ieltsType: "General",
    taskType: "Task 2",
    score: 6.5,
  },
  {
    submissionId: "mock-6",
    date: "14/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "General",
    taskType: "Task 1",
    score: 5.5,
  },
  {
    submissionId: "mock-7",
    date: "18/02/2026",
    essayType: "Practice",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: 8.0,
  },
];
