import type { GradingStatus } from "../types/GradingStatus";

export const mockSubmissionRows = [
  {
    submissionId: "mock-1",
    date: "01/02/2026",
    essayType: "Practice",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: 7.5,
    status: "ai_graded" as GradingStatus,
  },
  {
    submissionId: "mock-2",
    date: "03/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "General",
    taskType: "Task 1",
    score: null,
    status: "processing" as GradingStatus,
  },
  {
    submissionId: "mock-3",
    date: "05/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: null,
    status: "pending" as GradingStatus,
  },
  {
    submissionId: "mock-4",
    date: "06/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: 6.5,
    status: "teacher_reviewed" as GradingStatus,
  },
    {
    submissionId: "mock-5",
    date: "08/02/2026",
    essayType: "Practice",
    ieltsType: "General",
    taskType: "Task 1",
    score: null,
    status: "processing" as GradingStatus,
  },
  {
    submissionId: "mock-6",
    date: "10/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "Academic",
    taskType: "Task 2",
    score: null,
    status: "pending" as GradingStatus,
  },
  {
    submissionId: "mock-7",
    date: "12/02/2026",
    essayType: "Submitted Essay",
    ieltsType: "Academic",
    taskType: "Task 1",
    score: 6.5,
    status: "failed" as GradingStatus,
  },
];
