import "./AdminReportsPage.css";

type ReportRow = {
  reportName: string;
  type: string;
  generatedBy: string;
  dateGenerated: string;
  scope: string;
  status: string;
};

const reportData: ReportRow[] = [
  {
    reportName: "Weekly Usage Summary",
    type: "Usage",
    generatedBy: "System",
    dateGenerated: "10-Feb-26",
    scope: "System-wide",
    status: "Ready",
  },
  {
    reportName: "Student Progress – Feb",
    type: "Performance",
    generatedBy: "Admin",
    dateGenerated: "8-Feb-26",
    scope: "Cohort",
    status: "Ready",
  },
  {
    reportName: "Subscription Activity",
    type: "Subscription",
    generatedBy: "System",
    dateGenerated: "7-Feb-26",
    scope: "System-wide",
    status: "Ready",
  },
  {
    reportName: "Essay Feedback Trends",
    type: "Performance",
    generatedBy: "Admin",
    dateGenerated: "5-Feb-26",
    scope: "Cohort",
    status: "Ready",
  },
  {
    reportName: "Audit Activity Log",
    type: "Activity",
    generatedBy: "System",
    dateGenerated: "3-Feb-26",
    scope: "System-wide",
    status: "Ready",
  },
  {
    reportName: "Monthly Engagement",
    type: "Usage",
    generatedBy: "Admin",
    dateGenerated: "1-Feb-26",
    scope: "Cohort",
    status: "Ready",
  },
  {
    reportName: "System Health Snapshot",
    type: "Activity",
    generatedBy: "System",
    dateGenerated: "30-Jan-26",
    scope: "System-wide",
    status: "Ready",
  },
  {
    reportName: "System Health Snapshot",
    type: "Activity",
    generatedBy: "System",
    dateGenerated: "30-Jan-26",
    scope: "System-wide",
    status: "Ready",
  },
];

export default function AdminReportsPage() {
  return (
    <div className="admin-reports-page">
      <section className="admin-reports-header">
        <h1>Reports</h1>

        <div className="admin-reports-breadcrumb">
          <span className="reports-home-icon">⌂</span>
          <strong>Home &gt; Reports</strong>
        </div>
      </section>

      <section className="admin-reports-toolbar">
        <div className="reports-search-box">
          <span className="reports-menu-icon">☰</span>
          <input type="text" placeholder="Hinted search text" />
          <span className="reports-search-icon">⌕</span>
        </div>

        <button className="reports-export-button" title="Export report">
          ⇩
        </button>

        <button className="reports-filter-button" title="Filter reports">
          ≡
        </button>
      </section>

      <section className="reports-table-wrapper">
        <table className="reports-table">
          <thead>
            <tr>
              <th>Report Name</th>
              <th>Type</th>
              <th>Generated By</th>
              <th>Date Generated</th>
              <th>Scope</th>
              <th>Status</th>
              <th>Actions</th>
            </tr>
          </thead>

          <tbody>
            {reportData.map((report, index) => (
              <tr key={`${report.reportName}-${index}`}>
                <td>{report.reportName}</td>
                <td>{report.type}</td>
                <td>{report.generatedBy}</td>
                <td>{report.dateGenerated}</td>
                <td>{report.scope}</td>
                <td>{report.status}</td>
                <td>
                  <button className="reports-view-button">View</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="reports-pagination">
          « Prev | <strong>1</strong> | 2 | Next »
        </div>
      </section>
    </div>
  );
}